### ISSUE TITLE
Fix fadetiles + sand edge + room persistence edge case

### ISSUE THREAD

**Issue by Miepee** [AM2R-Community-Developers/ProfessorG64#15]
https://youtu.be/wrzyhv_8m3M

Repro steps:
- enter gamma shaft room
- collect the item
- destroy some sand
- enter fadetiles zone

how to fix:
```diff
var i;
for (i = 0; i < array_length_1d(tile_list); i += 1)
+{
+ if tile_exists(tile_list[i])
    tile_set_alpha(tile_list[i], falpha)
+}
```

**Comment by Jesright73** [comment]
Fixes applied; c25bc575c0ee9a54d990832ab77f0bf07af696fc and 211a81caf0c8d21357527367fdf4e7b6bc01797a.
