### ISSUE TITLE
Apply UMT compiler compatibility fixes (as needed)

### ISSUE THREAD

**Issue by Jesright73** [AM2R-Community-Developers/ProfessorG64#8]
The UMT compiler doesn't handle a few things properly:
- comparisons (boolean) within a math equation
- `return variable` within a switch statement
- some `while` loops

Code with these "features" will need to be rewritten to account for the modding tool's incompetence, if they are edited.

Code entries known to be affected:
**Boolean in an equation**
- `gml_Script_characterStepEvent` 
- `gml_Object_oEris_Draw_0` **UNUSED, OLD SERRIS CODE**
- `gml_Object_oErisHead_Draw_0` 
- `gml_Object_oA3LabDoor_Step_0`
- `gml_Object_oAutoadPlayer_Other_11` 
- `gml_Object_oA4PowerCell_Other_10` 
- `gml_Object_oMAlphaTriggerFirstCocoon_Alarm_0` 
- `gml_Object_oOptionsDisplay_Step_0` 
- `gml_Object_oSpaceJumpTrail_Draw_0`
- `gml_Object_oYumbo_Step_0` 

**OTHER**
- `gml_Script_chStepMovingCheck` _(broken `while` statements)_ **_AAAAHHHH!!!!!_**
- `gml_Script_scr_itemchange` _(return in a switch)_ 
- `gml_Object_oRm_a5c11lock_Collision_267` _(compiler error)_ **no error after changing to a `with` statement**
- `gml_Object_oAreaIntro_Step_0` _weird one, variable corruption?_

**Comment by Lojemiru** [comment]
Hopefully these will not be an issue given that we are working with the scripting components rather than direct decompilation, but this is good to note nonetheless.

**Comment by Jesright73** [comment]
Unfortunately, replacing code via scripts also uses the UMT de-compiler/re-compiler.

**Comment by Jesright73** [comment]
Another code entry affected by the compiler, this one throws an error:
`gml_Object_oRm_a5c11lock_Collision_267`
```gml
if (global.event[253] == 0)
    68400.lock = 4
instance_destroy()
```
![image](https://github.com/AM2R-Community-Developers/ProfessorG64/assets/79653967/1f47fafb-fb92-4892-9d8b-02b93bbab351)

**Comment by Jesright73** [comment]
updated list in opening comment.

**Comment by Lojemiru** [comment]
All rewritten thanks to some hard work from Jes earlier this evening.
